services:
  db:
    image: postgres:17
    env_file:
      - .env # TODO: determine if this should be .env.local
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - my_network

  system-profiler:
    build: ./system-profiler
    ports:
      - '8787:8787'
 
  ai-img-validator:
    build: ./ai-img-validator
    ports:
      - '8000:8000'

volumes:
  postgres_data_dev:

networks:
  my_network:
    driver: bridge
